export const TEMAS = ["institucional", "moderno", "minimalista"] as const;
export type Tema = (typeof TEMAS)[number];
export const temaConfig: Record<Tema, Record<string, string>> = {
  institucional: {
    "--bg-primary":     "#F8FAFC",
    "--bg-secondary":   "#F1F5F9",
    "--bg-card":        "#FFFFFF",
    "--bg-card-hover":  "#F8FAFC",
    "--text-primary":   "#0F172A",
    "--text-secondary": "#475569",
    "--text-muted":     "#94A3B8",
    "--accent":         "#1E3A8A",
    "--accent-hover":   "#1E40AF",
    "--accent-fg":      "#ffffff",
    "--success":        "#15803D",
    "--success-bg":     "#F0FDF4",
    "--error":          "#991B1B",
    "--error-bg":       "#FEF2F2",
    "--warning":        "#EA580C",
    "--warning-bg":     "#FFF7ED",
    "--info":           "#1E3A8A",
    "--info-bg":        "#EFF6FF",
    "--border":         "#E2E8F0",
    "--border-strong":  "#CBD5E1",
    "--ia":             "#6D28D9",
    "--ia-bg":          "#F5F3FF",
    "--shadow":         "0 1px 3px rgba(15,23,42,0.08)",
    "--btn-radius":     "4px",
    "--surface":        "#FFFFFF",
    "--primary-text":   "#FFFFFF",
    "--secondary":      "#E2E8F0",
    "--secondary-text": "#334155",
    "--card-radius":    "8px",
  },
  moderno: {
    "--bg-primary":     "#0B0F19",
    "--bg-secondary":   "#0F1626",
    "--bg-card":        "#151D30",
    "--bg-card-hover":  "#1A2540",
    "--text-primary":   "#F8FAFC",
    "--text-secondary": "#94A3B8",
    "--text-muted":     "#64748B",
    "--accent":         "#0EA5E9",
    "--accent-hover":   "#38BDF8",
    "--accent-fg":      "#0B0F19",
    "--success":        "#22C55E",
    "--success-bg":     "#052E16",
    "--error":          "#EF4444",
    "--error-bg":       "#2D0A0A",
    "--warning":        "#F97316",
    "--warning-bg":     "#2D1500",
    "--info":           "#0EA5E9",
    "--info-bg":        "#0A1628",
    "--border":         "#1E293B",
    "--border-strong":  "#2D4A6E",
    "--ia":             "#7C3AED",
    "--ia-bg":          "#1A0A2E",
    "--shadow":         "0 1px 4px rgba(0,0,0,0.40)",
    "--btn-radius":     "8px",
    "--surface":        "#151D30",
    "--primary-text":   "#0B0F19",
    "--secondary":      "#1E293B",
    "--secondary-text": "#94A3B8",
    "--card-radius":    "12px",
  },
  minimalista: {
    "--bg-primary":     "#F4F4F5",
    "--bg-secondary":   "#EFEFEF",
    "--bg-card":        "#FFFFFF",
    "--bg-card-hover":  "#F4F4F5",
    "--text-primary":   "#18181B",
    "--text-secondary": "#71717A",
    "--text-muted":     "#A1A1AA",
    "--accent":         "#000000",
    "--accent-hover":   "#27272A",
    "--accent-fg":      "#ffffff",
    "--success":        "#15803D",
    "--success-bg":     "#F0FDF4",
    "--error":          "#000000",
    "--error-bg":       "#F4F4F5",
    "--warning":        "#D97706",
    "--warning-bg":     "#FFFBEB",
    "--info":           "#000000",
    "--info-bg":        "#F4F4F5",
    "--border":         "#D4D4D8",
    "--border-strong":  "#A1A1AA",
    "--ia":             "#7C3AED",
    "--ia-bg":          "#FAF5FF",
    "--shadow":         "0 1px 2px rgba(0,0,0,0.06)",
    "--btn-radius":     "0px",
    "--surface":        "#FFFFFF",
    "--primary-text":   "#FFFFFF",
    "--secondary":      "#E4E4E7",
    "--secondary-text": "#52525B",
    "--card-radius":    "4px",
  },
};
