-- INDICES
-- Gerado por scripts/extrair_schema.mts em 2026-09-05.
-- NAO EDITE A MAO: regenere.

CREATE UNIQUE INDEX admin_users_pkey ON public.admin_users USING btree (user_id);
CREATE UNIQUE INDEX alertas_pkey ON public.alertas USING btree (id);
CREATE INDEX idx_alertas_proc ON public.alertas USING btree (processo_id);
CREATE INDEX idx_alertas_visto ON public.alertas USING btree (visto);
CREATE UNIQUE INDEX analise_itens_pkey ON public.analise_itens USING btree (id);
CREATE UNIQUE INDEX ux_analise_item_unico ON public.analise_itens USING btree (analise_id, processo_checklist_item_id);
CREATE UNIQUE INDEX analises_pkey ON public.analises USING btree (id);
CREATE UNIQUE INDEX analises_processo_id_numero_key ON public.analises USING btree (processo_id, numero);
CREATE UNIQUE INDEX analises_mac_pkey ON public.analises_mac USING btree (id);
CREATE UNIQUE INDEX analises_mac_unica_por_numero ON public.analises_mac USING btree (processo_codigo, tipo_processo, numero_analise) WHERE (excluido_em IS NULL);
CREATE INDEX idx_analises_lixeira ON public.analises_mac USING btree (excluido_em DESC) WHERE (excluido_em IS NOT NULL);
CREATE INDEX idx_analises_mac_assunto_id ON public.analises_mac USING btree (assunto_id);
CREATE UNIQUE INDEX assinaturas_decisao_id_papel_assinante_key ON public.assinaturas USING btree (decisao_id, papel_assinante);
CREATE UNIQUE INDEX assinaturas_pkey ON public.assinaturas USING btree (id);
CREATE UNIQUE INDEX assuntos_pkey ON public.assuntos USING btree (id);
CREATE UNIQUE INDEX assuntos_slug_key ON public.assuntos USING btree (slug);
CREATE UNIQUE INDEX auditoria_eventos_pkey ON public.auditoria_eventos USING btree (id);
CREATE INDEX idx_ae_analista ON public.auditoria_eventos USING btree (analista_id);
CREATE INDEX idx_ae_criado_em ON public.auditoria_eventos USING btree (criado_em DESC);
CREATE INDEX idx_ae_modulo ON public.auditoria_eventos USING btree (modulo, acao);
CREATE INDEX idx_ae_processo ON public.auditoria_eventos USING btree (processo_codigo);
CREATE INDEX idx_ae_sessao ON public.auditoria_eventos USING btree (sessao_id);
CREATE INDEX auditoria_eventos_backup_analista_id_idx ON public.auditoria_eventos_backup USING btree (analista_id);
CREATE INDEX auditoria_eventos_backup_criado_em_idx ON public.auditoria_eventos_backup USING btree (criado_em DESC);
CREATE INDEX auditoria_eventos_backup_modulo_acao_idx ON public.auditoria_eventos_backup USING btree (modulo, acao);
CREATE UNIQUE INDEX auditoria_eventos_backup_pkey ON public.auditoria_eventos_backup USING btree (id);
CREATE INDEX auditoria_eventos_backup_processo_codigo_idx ON public.auditoria_eventos_backup USING btree (processo_codigo);
CREATE INDEX auditoria_eventos_backup_sessao_id_idx ON public.auditoria_eventos_backup USING btree (sessao_id);
CREATE UNIQUE INDEX auditoria_log_pkey ON public.auditoria_log USING btree (id);
CREATE UNIQUE INDEX auditoria_log_backup_pkey ON public.auditoria_log_backup USING btree (id);
CREATE UNIQUE INDEX auditoria_sessoes_pkey ON public.auditoria_sessoes USING btree (id);
CREATE UNIQUE INDEX auditoria_sessoes_backup_pkey ON public.auditoria_sessoes_backup USING btree (id);
CREATE UNIQUE INDEX bdi_documentos_lei_pkey ON public.bdi_documentos_lei USING btree (id);
CREATE UNIQUE INDEX bdi_documentos_lei_backup_pkey ON public.bdi_documentos_lei_backup USING btree (id);
CREATE UNIQUE INDEX bdi_lei_fragmentos_pkey ON public.bdi_lei_fragmentos USING btree (id);
CREATE INDEX idx_fragmentos_documento ON public.bdi_lei_fragmentos USING btree (documento_id);
CREATE INDEX idx_fragmentos_embedding ON public.bdi_lei_fragmentos USING hnsw (embedding vector_cosine_ops);
CREATE INDEX bdi_lei_fragmentos_backup_documento_id_idx ON public.bdi_lei_fragmentos_backup USING btree (documento_id);
CREATE INDEX bdi_lei_fragmentos_backup_embedding_idx ON public.bdi_lei_fragmentos_backup USING hnsw (embedding vector_cosine_ops);
CREATE UNIQUE INDEX bdi_lei_fragmentos_backup_pkey ON public.bdi_lei_fragmentos_backup USING btree (id);
CREATE UNIQUE INDEX bdi_snapshots_pkey ON public.bdi_snapshots USING btree (id);
CREATE INDEX idx_bdi_snapshots_gerado_em ON public.bdi_snapshots USING btree (gerado_em DESC);
CREATE INDEX idx_bdi_snapshots_tipo ON public.bdi_snapshots USING btree (tipo);
CREATE UNIQUE INDEX bip_anotacoes_usuario_pkey ON public.bip_anotacoes_usuario USING btree (id);
CREATE UNIQUE INDEX bip_anotacoes_usuario_usuario_id_lei_id_pagina_key ON public.bip_anotacoes_usuario USING btree (usuario_id, lei_id, pagina);
CREATE INDEX idx_bip_anotacoes_pagina ON public.bip_anotacoes_usuario USING btree (usuario_id, lei_id, pagina);
CREATE INDEX idx_bip_anotacoes_usuario_lei ON public.bip_anotacoes_usuario USING btree (usuario_id, lei_id);
CREATE UNIQUE INDEX bip_historico_anotacoes_pkey ON public.bip_historico_anotacoes USING btree (id);
CREATE INDEX idx_bip_historico_usuario_lei ON public.bip_historico_anotacoes USING btree (usuario_id, lei_id, criado_em DESC);
CREATE UNIQUE INDEX cadastro_processo_pkey ON public.cadastro_processo USING btree (id);
CREATE UNIQUE INDEX cadastro_processo_processo_id_key ON public.cadastro_processo USING btree (processo_id);
CREATE UNIQUE INDEX chat_mensagens_pkey ON public.chat_mensagens USING btree (id);
CREATE UNIQUE INDEX checklist_instancias_pkey ON public.checklist_instancias USING btree (id);
CREATE UNIQUE INDEX checklist_instancias_processo_id_key ON public.checklist_instancias USING btree (processo_id);
CREATE INDEX idx_checklist_instancias_processo_id ON public.checklist_instancias USING btree (processo_id);
CREATE UNIQUE INDEX checklist_item_estatistica_pkey ON public.checklist_item_estatistica USING btree (item_modelo_id);
CREATE UNIQUE INDEX checklist_items_codigo_key ON public.checklist_items USING btree (codigo);
CREATE UNIQUE INDEX checklist_items_pkey ON public.checklist_items USING btree (id);
CREATE UNIQUE INDEX checklist_itens_codigo_unique ON public.checklist_itens USING btree (codigo);
CREATE UNIQUE INDEX checklist_itens_pkey ON public.checklist_itens USING btree (id);
CREATE UNIQUE INDEX checklist_itens_procedimento_codigo_key ON public.checklist_itens USING btree (procedimento, codigo);
CREATE UNIQUE INDEX checklist_itens_instancia_pkey ON public.checklist_itens_instancia USING btree (id);
CREATE INDEX idx_checklist_itens_instancia_instancia_id ON public.checklist_itens_instancia USING btree (instancia_id);
CREATE INDEX idx_checklist_itens_instancia_status ON public.checklist_itens_instancia USING btree (status);
CREATE UNIQUE INDEX checklist_modelo_itens_pkey ON public.checklist_modelo_itens USING btree (id);
CREATE INDEX idx_checklist_modelo_itens_modelo ON public.checklist_modelo_itens USING btree (checklist_modelo_id);
CREATE INDEX ix_modelo_itens_modelo ON public.checklist_modelo_itens USING btree (modelo_id);
CREATE UNIQUE INDEX checklist_modelos_pkey ON public.checklist_modelos USING btree (id);
CREATE UNIQUE INDEX ux_modelo_global_tipo_versao ON public.checklist_modelos USING btree (tipo_processo, versao) WHERE ((owner_equipe_id IS NULL) AND (gerencia_id IS NULL));
CREATE UNIQUE INDEX ux_modelo_por_gerencia_tipo_versao ON public.checklist_modelos USING btree (tipo_processo, gerencia_id, versao) WHERE ((owner_equipe_id IS NULL) AND (gerencia_id IS NOT NULL));
CREATE UNIQUE INDEX checklist_respostas_pkey ON public.checklist_respostas USING btree (id);
CREATE UNIQUE INDEX checklist_respostas_processo_id_checklist_item_id_analise_i_key ON public.checklist_respostas USING btree (processo_id, checklist_item_id, analise_id);
CREATE INDEX idx_checklist_respostas_analise ON public.checklist_respostas USING btree (analise_id);
CREATE INDEX idx_checklist_respostas_item ON public.checklist_respostas USING btree (checklist_item_id);
CREATE INDEX idx_checklist_respostas_processo ON public.checklist_respostas USING btree (processo_id);
CREATE UNIQUE INDEX config_urbis_pkey ON public.config_urbis USING btree (chave);
CREATE UNIQUE INDEX decisoes_pkey ON public.decisoes USING btree (id);
CREATE UNIQUE INDEX despacho_padroes_pkey ON public.despacho_padroes USING btree (id);
CREATE INDEX idx_despacho_padroes_bucket ON public.despacho_padroes USING btree (assunto_id, modulo, tipo_despacho) WHERE ativo;
CREATE UNIQUE INDEX idx_despacho_padroes_titulo_unico ON public.despacho_padroes USING btree (assunto_id, modulo, tipo_despacho, titulo) WHERE ativo;
CREATE UNIQUE INDEX despachos_pkey ON public.despachos USING btree (id);
CREATE INDEX idx_despachos_processo_assunto ON public.despachos USING btree (processo_id, assunto_id);
CREATE UNIQUE INDEX ux_despacho_proc_num ON public.despachos USING btree (processo_id, numero);
CREATE UNIQUE INDEX diretorias_pkey ON public.diretorias USING btree (id);
CREATE UNIQUE INDEX documentos_pkey ON public.documentos USING btree (id);
CREATE UNIQUE INDEX documentos_processo_id_tipo_versao_key ON public.documentos USING btree (processo_id, tipo, versao);
CREATE INDEX idx_docs_proc ON public.documentos USING btree (processo_id);
CREATE INDEX idx_docs_tipo ON public.documentos USING btree (tipo);
CREATE UNIQUE INDEX documentos_lidos_pkey ON public.documentos_lidos USING btree (id);
CREATE UNIQUE INDEX documentos_processo_pkey ON public.documentos_processo USING btree (id);
CREATE INDEX idx_documentos_processo_assunto_tipo ON public.documentos_processo USING btree (processo_id, assunto_id, tipo_documento);
CREATE INDEX idx_documentos_processo_processo_id ON public.documentos_processo USING btree (processo_id);
CREATE INDEX idx_documentos_processo_tipo ON public.documentos_processo USING btree (tipo_documento);
CREATE UNIQUE INDEX equipe_auth_uid_unique ON public.equipe USING btree (auth_uid);
CREATE UNIQUE INDEX equipe_email_key ON public.equipe USING btree (email);
CREATE UNIQUE INDEX equipe_matricula_key ON public.equipe USING btree (matricula);
CREATE UNIQUE INDEX equipe_matricula_unique ON public.equipe USING btree (matricula);
CREATE UNIQUE INDEX equipe_pkey ON public.equipe USING btree (id);
CREATE UNIQUE INDEX equipe_gerencias_pkey ON public.equipe_gerencias USING btree (equipe_id, gerencia_id);
CREATE UNIQUE INDEX equipe_roles_pkey ON public.equipe_roles USING btree (equipe_id, role);
CREATE UNIQUE INDEX etapa_tempo_sessoes_pkey ON public.etapa_tempo_sessoes USING btree (id);
CREATE INDEX idx_tempo_etapa ON public.etapa_tempo_sessoes USING btree (etapa_id);
CREATE INDEX idx_tempo_proc ON public.etapa_tempo_sessoes USING btree (processo_id);
CREATE UNIQUE INDEX eventos_pkey ON public.eventos USING btree (id);
CREATE UNIQUE INDEX eventos_unique_status ON public.eventos USING btree (processo_id, tipo, etapa, descricao);
CREATE UNIQUE INDEX eventos_unique_status_fix ON public.eventos USING btree (processo_id, tipo, etapa, descricao);
CREATE UNIQUE INDEX eventos_unique_status_idx ON public.eventos USING btree (processo_id, tipo, etapa, descricao, data_evento);
CREATE UNIQUE INDEX formato_identificadores_pkey ON public.formato_identificadores USING btree (id);
CREATE UNIQUE INDEX gerencias_pkey ON public.gerencias USING btree (id);
CREATE INDEX ix_gerencias_diretoria ON public.gerencias USING btree (diretoria_id);
CREATE UNIQUE INDEX ux_gerencias_unicas ON public.gerencias USING btree (diretoria_id, nome);
CREATE UNIQUE INDEX impeditivos_pkey ON public.impeditivos USING btree (id);
CREATE INDEX idx_lip_abas_assunto_id ON public.lip_abas USING btree (assunto_id);
CREATE UNIQUE INDEX lip_abas_pkey ON public.lip_abas USING btree (id);
CREATE INDEX lip_campos_aba_id_idx ON public.lip_campos USING btree (aba_id);
CREATE UNIQUE INDEX lip_campos_pkey ON public.lip_campos USING btree (id);
CREATE UNIQUE INDEX lip_decisoes_item_pkey ON public.lip_decisoes_item USING btree (processo_id, ordem);
CREATE UNIQUE INDEX lip_decisoes_item_unique_processo_ordem ON public.lip_decisoes_item USING btree (processo_id, ordem);
CREATE UNIQUE INDEX lip_jobs_pkey ON public.lip_jobs USING btree (id);
CREATE UNIQUE INDEX lip_processo_atual_pkey ON public.lip_processo_atual USING btree (id);
CREATE INDEX idx_lip_prompts_assunto_id ON public.lip_prompts USING btree (assunto_id);
CREATE UNIQUE INDEX lip_prompts_pkey ON public.lip_prompts USING btree (id);
CREATE INDEX idx_lip_prompts_historico_chave_salvo_em ON public.lip_prompts_historico USING btree (prompt_chave, salvo_em DESC);
CREATE UNIQUE INDEX lip_prompts_historico_pkey ON public.lip_prompts_historico USING btree (id);
CREATE UNIQUE INDEX lip_resultados_pkey ON public.lip_resultados USING btree (id);
CREATE INDEX idx_logradouros_bairro ON public.logradouros USING btree (bairro);
CREATE INDEX idx_logradouros_logradouro ON public.logradouros USING btree (nome_logradouro);
CREATE UNIQUE INDEX logradouros_pkey ON public.logradouros USING btree (id);
CREATE INDEX mac_bip_vinculos_frag_idx ON public.mac_bip_vinculos USING btree (bip_fragmento_id);
CREATE INDEX mac_bip_vinculos_item_idx ON public.mac_bip_vinculos USING btree (mac_item_id);
CREATE UNIQUE INDEX mac_bip_vinculos_mac_item_id_bip_fragmento_id_key ON public.mac_bip_vinculos USING btree (mac_item_id, bip_fragmento_id);
CREATE UNIQUE INDEX mac_bip_vinculos_pkey ON public.mac_bip_vinculos USING btree (id);
CREATE INDEX idx_mac_checklist_itens_chave_lip ON public.mac_checklist_itens USING btree (chave_lip) WHERE (chave_lip IS NOT NULL);
CREATE INDEX idx_mac_itens_indeferimento ON public.mac_checklist_itens USING btree (modelo_id) WHERE gera_indeferimento;
CREATE UNIQUE INDEX mac_checklist_itens_pkey ON public.mac_checklist_itens USING btree (id);
CREATE INDEX mac_checklist_itens_historico_criado_em_idx ON public.mac_checklist_itens_historico USING btree (criado_em);
CREATE INDEX mac_checklist_itens_historico_item_idx ON public.mac_checklist_itens_historico USING btree (item_id);
CREATE UNIQUE INDEX mac_checklist_itens_historico_pkey ON public.mac_checklist_itens_historico USING btree (id);
CREATE INDEX mac_checklist_itens_historico_tipo_processo_idx ON public.mac_checklist_itens_historico USING btree (tipo_processo);
CREATE INDEX idx_mac_checklist_modelos_assunto_id ON public.mac_checklist_modelos USING btree (assunto_id);
CREATE UNIQUE INDEX mac_checklist_modelos_pkey ON public.mac_checklist_modelos USING btree (id);
CREATE UNIQUE INDEX mac_execucoes_pkey ON public.mac_execucoes USING btree (id);
CREATE INDEX mac_execucoes_processo_idx ON public.mac_execucoes USING btree (processo_id);
CREATE INDEX mac_execucoes_status_idx ON public.mac_execucoes USING btree (status);
CREATE UNIQUE INDEX mac_glossario_pkey ON public.mac_glossario USING btree (id);
CREATE UNIQUE INDEX mac_glossario_termo_key ON public.mac_glossario USING btree (termo);
CREATE UNIQUE INDEX mac_historico_pkey ON public.mac_historico USING btree (id);
CREATE INDEX mac_lip_vinculos_chave_idx ON public.mac_lip_vinculos USING btree (lip_chave);
CREATE INDEX mac_lip_vinculos_item_idx ON public.mac_lip_vinculos USING btree (mac_item_id);
CREATE UNIQUE INDEX mac_lip_vinculos_mac_item_id_lip_chave_key ON public.mac_lip_vinculos USING btree (mac_item_id, lip_chave);
CREATE UNIQUE INDEX mac_lip_vinculos_pkey ON public.mac_lip_vinculos USING btree (id);
CREATE UNIQUE INDEX mac_resultados_item_execucao_id_mac_item_id_key ON public.mac_resultados_item USING btree (execucao_id, mac_item_id);
CREATE INDEX mac_resultados_item_execucao_idx ON public.mac_resultados_item USING btree (execucao_id);
CREATE INDEX mac_resultados_item_item_idx ON public.mac_resultados_item USING btree (mac_item_id);
CREATE UNIQUE INDEX mac_resultados_item_pkey ON public.mac_resultados_item USING btree (id);
CREATE INDEX mac_resultados_item_revisao_idx ON public.mac_resultados_item USING btree (requer_revisao) WHERE requer_revisao;
CREATE INDEX mac_resultados_revisoes_item_idx ON public.mac_resultados_revisoes USING btree (resultado_item_id);
CREATE UNIQUE INDEX mac_resultados_revisoes_pkey ON public.mac_resultados_revisoes USING btree (id);
CREATE INDEX idx_mac_slot5_filtros_ativo ON public.mac_slot5_filtros USING btree (ativo, ordem);
CREATE UNIQUE INDEX mac_slot5_filtros_pkey ON public.mac_slot5_filtros USING btree (id);
CREATE INDEX mac_vinculos_propostas_item_idx ON public.mac_vinculos_propostas USING btree (mac_item_id);
CREATE UNIQUE INDEX mac_vinculos_propostas_pendente_bip_idx ON public.mac_vinculos_propostas USING btree (mac_item_id, bip_fragmento_id) WHERE ((status = 'pendente'::text) AND (tipo = 'BIP'::text));
CREATE UNIQUE INDEX mac_vinculos_propostas_pendente_lip_idx ON public.mac_vinculos_propostas USING btree (mac_item_id, lip_chave) WHERE ((status = 'pendente'::text) AND (tipo = 'LIP'::text));
CREATE UNIQUE INDEX mac_vinculos_propostas_pkey ON public.mac_vinculos_propostas USING btree (id);
CREATE INDEX mac_vinculos_propostas_status_idx ON public.mac_vinculos_propostas USING btree (status);
CREATE INDEX idx_mdp_busca_norm_trgm ON public.mdp_registros USING gin (busca_norm gin_trgm_ops);
CREATE INDEX mdp_registros_criado_em_idx ON public.mdp_registros USING btree (criado_em DESC);
CREATE UNIQUE INDEX mdp_registros_pkey ON public.mdp_registros USING btree (id);
CREATE INDEX mdp_registros_processo_idx ON public.mdp_registros USING btree (processo_codigo);
CREATE INDEX mdp_registros_usuario_idx ON public.mdp_registros USING btree (usuario_id);
CREATE INDEX idx_mhd_conteudos_extrator ON public.mhd_conteudos USING btree (extrator_versao);
CREATE UNIQUE INDEX mhd_conteudos_hash_key ON public.mhd_conteudos USING btree (hash);
CREATE UNIQUE INDEX mhd_conteudos_pkey ON public.mhd_conteudos USING btree (id);
CREATE INDEX idx_mhd_documentos_assunto ON public.mhd_documentos USING btree (assunto_id);
CREATE INDEX idx_mhd_documentos_processo ON public.mhd_documentos USING btree (processo_codigo);
CREATE UNIQUE INDEX mhd_documentos_identidade ON public.mhd_documentos USING btree (processo_codigo, papel, escopo);
CREATE UNIQUE INDEX mhd_documentos_pkey ON public.mhd_documentos USING btree (id);
CREATE INDEX idx_mhd_eventos_processo ON public.mhd_eventos USING btree (processo_codigo, criado_em DESC);
CREATE INDEX idx_mhd_eventos_tipo ON public.mhd_eventos USING btree (tipo);
CREATE UNIQUE INDEX mhd_eventos_pkey ON public.mhd_eventos USING btree (id);
CREATE INDEX idx_mhd_visao_documento ON public.mhd_interpretacoes_visao USING btree (hash_documento);
CREATE UNIQUE INDEX mhd_interpretacoes_visao_hash_documento_pagina_regiao_hash__key ON public.mhd_interpretacoes_visao USING btree (hash_documento, pagina, regiao_hash, receita_hash, modelo);
CREATE UNIQUE INDEX mhd_interpretacoes_visao_pkey ON public.mhd_interpretacoes_visao USING btree (id);
CREATE INDEX idx_mhd_resultados_execucao ON public.mhd_resultados_campo USING btree (execucao_id);
CREATE INDEX idx_mhd_resultados_processo ON public.mhd_resultados_campo USING btree (processo_codigo, modulo, slot);
CREATE INDEX idx_mhd_resultados_resultado ON public.mhd_resultados_campo USING btree (resultado);
CREATE UNIQUE INDEX mhd_resultados_campo_pkey ON public.mhd_resultados_campo USING btree (id);
CREATE UNIQUE INDEX uq_mhd_resultados_execucao ON public.mhd_resultados_campo USING btree (processo_codigo, modulo, slot, chave, execucao_id);
CREATE UNIQUE INDEX uq_mhd_resultados_vigente ON public.mhd_resultados_campo USING btree (processo_codigo, modulo, slot, chave) WHERE vigente;
CREATE INDEX idx_mhd_versoes_conteudo ON public.mhd_versoes USING btree (conteudo_id);
CREATE INDEX idx_mhd_versoes_documento ON public.mhd_versoes USING btree (documento_id, versao DESC);
CREATE INDEX idx_mhd_versoes_hash ON public.mhd_versoes USING btree (hash);
CREATE UNIQUE INDEX mhd_versoes_documento_id_versao_key ON public.mhd_versoes USING btree (documento_id, versao);
CREATE UNIQUE INDEX mhd_versoes_pkey ON public.mhd_versoes USING btree (id);
CREATE INDEX idx_mrp_calendario_usuario ON public.mrp_calendario USING btree (usuario_id, ano, mes);
CREATE UNIQUE INDEX mrp_calendario_pkey ON public.mrp_calendario USING btree (id);
CREATE UNIQUE INDEX mrp_calendario_usuario_id_mes_ano_key ON public.mrp_calendario USING btree (usuario_id, mes, ano);
CREATE UNIQUE INDEX mrp_calendario_backup_pkey ON public.mrp_calendario_backup USING btree (id);
CREATE INDEX mrp_calendario_backup_usuario_id_ano_mes_idx ON public.mrp_calendario_backup USING btree (usuario_id, ano, mes);
CREATE UNIQUE INDEX mrp_calendario_backup_usuario_id_mes_ano_key ON public.mrp_calendario_backup USING btree (usuario_id, mes, ano);
CREATE INDEX idx_mrp_meta_historico_vigencia ON public.mrp_meta_historico USING btree (vigente_desde DESC);
CREATE INDEX idx_mrp_meta_usuario_vigencia ON public.mrp_meta_historico USING btree (usuario_id, vigente_desde DESC);
CREATE UNIQUE INDEX mrp_meta_historico_pkey ON public.mrp_meta_historico USING btree (id);
CREATE UNIQUE INDEX uq_mrp_meta_geral ON public.mrp_meta_historico USING btree (vigente_desde) WHERE (usuario_id IS NULL);
CREATE UNIQUE INDEX uq_mrp_meta_usuario ON public.mrp_meta_historico USING btree (usuario_id, vigente_desde) WHERE (usuario_id IS NOT NULL);
CREATE UNIQUE INDEX mrp_pontuacao_pkey ON public.mrp_pontuacao USING btree (id);
CREATE UNIQUE INDEX mrp_pontuacao_backup_pkey ON public.mrp_pontuacao_backup USING btree (id);
CREATE INDEX idx_mrp_pontuacao_historico_regra ON public.mrp_pontuacao_historico USING btree (regra_id, vigente_desde DESC);
CREATE UNIQUE INDEX mrp_pontuacao_historico_pkey ON public.mrp_pontuacao_historico USING btree (id);
CREATE INDEX idx_mrp_registros_assunto ON public.mrp_registros USING btree (assunto_id);
CREATE INDEX idx_mrp_registros_data ON public.mrp_registros USING btree (data_despacho DESC);
CREATE INDEX idx_mrp_registros_gerencia ON public.mrp_registros USING btree (gerencia, ano, mes);
CREATE INDEX idx_mrp_registros_processo ON public.mrp_registros USING btree (processo_codigo);
CREATE INDEX idx_mrp_registros_usuario_assunto_periodo ON public.mrp_registros USING btree (usuario_id, assunto_id, ano, mes);
CREATE INDEX idx_mrp_registros_usuario_mes ON public.mrp_registros USING btree (usuario_id, ano, mes);
CREATE UNIQUE INDEX mrp_registros_auto_unico ON public.mrp_registros USING btree (usuario_id, processo_codigo, tipo_despacho, numero_analise) WHERE (auto_gerado = true);
CREATE UNIQUE INDEX mrp_registros_pkey ON public.mrp_registros USING btree (id);
CREATE UNIQUE INDEX mrp_registros_usuario_despacho_unique ON public.mrp_registros USING btree (usuario_id, numero_despacho);
CREATE INDEX mrp_registros_backup_data_despacho_idx ON public.mrp_registros_backup USING btree (data_despacho DESC);
CREATE UNIQUE INDEX mrp_registros_backup_pkey ON public.mrp_registros_backup USING btree (id);
CREATE INDEX mrp_registros_backup_processo_codigo_idx ON public.mrp_registros_backup USING btree (processo_codigo);
CREATE INDEX mrp_registros_backup_usuario_id_ano_mes_idx ON public.mrp_registros_backup USING btree (usuario_id, ano, mes);
CREATE UNIQUE INDEX mrp_registros_backup_usuario_id_processo_codigo_tipo_despac_idx ON public.mrp_registros_backup USING btree (usuario_id, processo_codigo, tipo_despacho, numero_analise) WHERE (auto_gerado = true);
CREATE UNIQUE INDEX notificacoes_pkey ON public.notificacoes USING btree (id);
CREATE INDEX idx_obs_cod_abertas ON public.obs_cod USING btree (criado_em DESC) WHERE (situacao = 'aberto'::text);
CREATE UNIQUE INDEX obs_cod_pkey ON public.obs_cod USING btree (id);
CREATE UNIQUE INDEX papeis_ativos_pkey ON public.papeis_ativos USING btree (papel);
CREATE UNIQUE INDEX porte_config_pkey ON public.porte_config USING btree (id);
CREATE INDEX ix_proc_checklist_proc ON public.processo_checklist_itens USING btree (processo_id);
CREATE UNIQUE INDEX processo_checklist_itens_pkey ON public.processo_checklist_itens USING btree (id);
CREATE UNIQUE INDEX ux_proc_checklist_item_unico ON public.processo_checklist_itens USING btree (processo_id, checklist_modelo_item_id);
CREATE INDEX idx_pdi_proc_tipo ON public.processo_documento_ingestao USING btree (processo_id, tipo_documento, status_doc, coletado_em DESC);
CREATE INDEX idx_pdi_proc_tipo_status_data ON public.processo_documento_ingestao USING btree (processo_id, tipo_documento, status_doc, data_documento DESC, coletado_em DESC);
CREATE INDEX idx_pdi_sei_doc_id ON public.processo_documento_ingestao USING btree (sei_doc_id);
CREATE UNIQUE INDEX processo_documento_ingestao_pkey ON public.processo_documento_ingestao USING btree (id);
CREATE UNIQUE INDEX processo_documento_ingestao_processo_id_tipo_documento_hash_key ON public.processo_documento_ingestao USING btree (processo_id, tipo_documento, hash_conteudo);
CREATE UNIQUE INDEX uq_pdi_processo_docsei ON public.processo_documento_ingestao USING btree (processo_id, sei_doc_id);
CREATE INDEX idx_etapas_processo ON public.processo_etapas USING btree (processo_id, criado_em DESC);
CREATE UNIQUE INDEX processo_etapas_pkey ON public.processo_etapas USING btree (id);
CREATE UNIQUE INDEX uq_etapa_numero ON public.processo_etapas USING btree (processo_id, tipo_etapa, numero);
CREATE INDEX idx_eventos_processo ON public.processo_eventos USING btree (processo_id, criado_em DESC);
CREATE INDEX idx_processo_eventos_matricula ON public.processo_eventos USING btree (matricula);
CREATE UNIQUE INDEX processo_eventos_pkey ON public.processo_eventos USING btree (id);
CREATE INDEX processo_fila_overrides_idx ON public.processo_fila_overrides USING btree (analista_id, posicao, criado_em);
CREATE UNIQUE INDEX processo_fila_overrides_pkey ON public.processo_fila_overrides USING btree (id);
CREATE INDEX processo_fila_overrides_processo_idx ON public.processo_fila_overrides USING btree (processo_id);
CREATE UNIQUE INDEX processo_historico_pkey ON public.processo_historico USING btree (id);
CREATE INDEX processo_historico_processo_idx ON public.processo_historico USING btree (processo_id);
CREATE INDEX processo_prazo_interessado_bloq_idx ON public.processo_prazo_interessado USING btree (bloqueado, dias_corridos_sem_retorno);
CREATE UNIQUE INDEX processo_prazo_interessado_pkey ON public.processo_prazo_interessado USING btree (processo_id);
CREATE INDEX idx_processo_profissionais_processo ON public.processo_profissionais USING btree (processo_id);
CREATE INDEX idx_processo_profissionais_profissional ON public.processo_profissionais USING btree (profissional_id);
CREATE UNIQUE INDEX processo_profissionais_pkey ON public.processo_profissionais USING btree (id);
CREATE UNIQUE INDEX processo_profissionais_processo_id_profissional_id_papel_key ON public.processo_profissionais USING btree (processo_id, profissional_id, papel);
CREATE UNIQUE INDEX processo_tempo_pkey ON public.processo_tempo USING btree (processo_id);
CREATE INDEX idx_processos_ativos ON public.processos USING btree (criado_em DESC) WHERE (excluido_em IS NULL);
CREATE INDEX idx_processos_checklist_modelo_id ON public.processos USING btree (checklist_modelo_id);
CREATE UNIQUE INDEX idx_processos_codigo_tipo ON public.processos USING btree (codigo, tipo_processo);
CREATE INDEX idx_processos_lixeira ON public.processos USING btree (excluido_em DESC) WHERE (excluido_em IS NOT NULL);
CREATE UNIQUE INDEX processos_codigo_unique ON public.processos USING btree (codigo);
CREATE UNIQUE INDEX processos_pkey ON public.processos USING btree (id);
CREATE UNIQUE INDEX ux_processos_numero_sei ON public.processos USING btree (numero_sei) WHERE ((numero_sei IS NOT NULL) AND (btrim(numero_sei) <> ''::text) AND (status <> 'ARQUIVADO_DUPLICADO'::status_processo_enum));
CREATE INDEX idx_profissionais_cau ON public.profissionais USING btree (cau) WHERE (cau IS NOT NULL);
CREATE INDEX idx_profissionais_crea ON public.profissionais USING btree (crea) WHERE (crea IS NOT NULL);
CREATE INDEX idx_profissionais_merged_into ON public.profissionais USING btree (merged_into_id) WHERE (merged_into_id IS NOT NULL);
CREATE INDEX idx_profissionais_nome_normalizado ON public.profissionais USING btree (nome_normalizado);
CREATE UNIQUE INDEX profissionais_pkey ON public.profissionais USING btree (id);
CREATE UNIQUE INDEX profissionais_backfill_execucoes_pkey ON public.profissionais_backfill_execucoes USING btree (id);
CREATE UNIQUE INDEX rh_log_pkey ON public.rh_log USING btree (id);
CREATE INDEX idx_solic_proc ON public.solicitacoes_despacho_extra USING btree (processo_id);
CREATE INDEX idx_solic_status ON public.solicitacoes_despacho_extra USING btree (status);
CREATE UNIQUE INDEX solicitacoes_despacho_extra_pkey ON public.solicitacoes_despacho_extra USING btree (id);
CREATE UNIQUE INDEX solicitacoes_etapa6_pkey ON public.solicitacoes_etapa6 USING btree (id);
CREATE UNIQUE INDEX tipos_documento_nome_key ON public.tipos_documento USING btree (nome);
CREATE UNIQUE INDEX tipos_documento_pkey ON public.tipos_documento USING btree (id);
CREATE INDEX idx_urbi_comandos_voz_usuario_data ON public.urbi_comandos_voz USING btree (usuario_id, criado_em DESC);
CREATE UNIQUE INDEX urbi_comandos_voz_pkey ON public.urbi_comandos_voz USING btree (id);
CREATE UNIQUE INDEX urbi_config_chave_key ON public.urbi_config USING btree (chave);
CREATE UNIQUE INDEX urbi_config_pkey ON public.urbi_config USING btree (id);
CREATE UNIQUE INDEX urbi_historico_pkey ON public.urbi_historico USING btree (id);
CREATE INDEX urbi_historico_processo_codigo_idx ON public.urbi_historico USING btree (processo_codigo);
CREATE UNIQUE INDEX urbi_legislacao_pkey ON public.urbi_legislacao USING btree (id);
CREATE INDEX urbi_radar_retratos_campos_consulta_idx ON public.urbi_radar_retratos USING gin (campos_consulta);
CREATE INDEX urbi_radar_retratos_fila_idx ON public.urbi_radar_retratos USING btree (estado, criado_em) WHERE (estado = ANY (ARRAY['pendente'::text, 'em_atualizacao'::text]));
CREATE UNIQUE INDEX urbi_radar_retratos_pkey ON public.urbi_radar_retratos USING btree (id);
CREATE INDEX urbi_radar_retratos_processo_versao_idx ON public.urbi_radar_retratos USING btree (processo_codigo, versao DESC);
CREATE INDEX urbi_sugestoes_estado_idx ON public.urbi_sugestoes USING btree (estado);
CREATE UNIQUE INDEX urbi_sugestoes_pkey ON public.urbi_sugestoes USING btree (id);
CREATE UNIQUE INDEX urbi_sugestoes_processo_codigo_tipo_chave_key ON public.urbi_sugestoes USING btree (processo_codigo, tipo, chave);
CREATE INDEX urbi_sugestoes_processo_idx ON public.urbi_sugestoes USING btree (processo_codigo);
CREATE INDEX urbi_sugestoes_slot_idx ON public.urbi_sugestoes USING btree (slot);
CREATE INDEX idx_urbis_api_calls_criado_em ON public.urbis_api_calls USING btree (criado_em DESC);
CREATE INDEX urbis_api_calls_criado_em_idx ON public.urbis_api_calls USING btree (criado_em);
CREATE INDEX urbis_api_calls_modulo_idx ON public.urbis_api_calls USING btree (modulo);
CREATE UNIQUE INDEX urbis_api_calls_pkey ON public.urbis_api_calls USING btree (id);
CREATE INDEX urbis_api_calls_processo_idx ON public.urbis_api_calls USING btree (processo_codigo);
CREATE INDEX urbis_aportes_data_hora_idx ON public.urbis_aportes USING btree (data_hora);
CREATE UNIQUE INDEX urbis_aportes_pkey ON public.urbis_aportes USING btree (id);
CREATE UNIQUE INDEX urbis_config_pkey ON public.urbis_config USING btree (id);
CREATE UNIQUE INDEX urbis_lip_cores_pkey ON public.urbis_lip_cores USING btree (ator_nome);
CREATE INDEX idx_lip_docs_grupo ON public.urbis_lip_documentos USING btree (processo_id, tipo_documento, doc_chave);
CREATE UNIQUE INDEX uq_lip_docs_ultima_versao ON public.urbis_lip_documentos USING btree (processo_id, tipo_documento, doc_chave) WHERE (eh_ultima_versao = true);
CREATE UNIQUE INDEX urbis_lip_documentos_pkey ON public.urbis_lip_documentos USING btree (id);
CREATE UNIQUE INDEX urbis_lip_evento_tipos_nome_evento_key ON public.urbis_lip_evento_tipos USING btree (nome_evento);
CREATE UNIQUE INDEX urbis_lip_evento_tipos_pkey ON public.urbis_lip_evento_tipos USING btree (id);
CREATE INDEX idx_lip_ref_documento ON public.urbis_lip_eventos USING btree (referencia_documento);
CREATE INDEX idx_urbis_lip_eventos_processo ON public.urbis_lip_eventos USING btree (processo_id, iniciado_em);
CREATE UNIQUE INDEX urbis_lip_eventos_pkey ON public.urbis_lip_eventos USING btree (id);
CREATE UNIQUE INDEX urbis_lip_fluxo_etapas_etapa_codigo_key ON public.urbis_lip_fluxo_etapas USING btree (etapa_codigo);
CREATE UNIQUE INDEX urbis_lip_fluxo_etapas_pkey ON public.urbis_lip_fluxo_etapas USING btree (id);
CREATE UNIQUE INDEX uq_lip_indice_processo_referencia ON public.urbis_lip_indice USING btree (processo_id, item_referencia);
CREATE UNIQUE INDEX uq_urbis_lip_indice_processo_referencia ON public.urbis_lip_indice USING btree (processo_id, item_referencia);
CREATE UNIQUE INDEX urbis_lip_indice_pkey ON public.urbis_lip_indice USING btree (id);
CREATE UNIQUE INDEX urbis_logs_pkey ON public.urbis_logs USING btree (id);
CREATE INDEX urbis_logs_processo_idx ON public.urbis_logs USING btree (processo_id, created_at DESC);
CREATE INDEX urbis_notif_lida_idx ON public.urbis_notificacoes USING btree (lida, created_at DESC);
CREATE INDEX urbis_notif_processo_idx ON public.urbis_notificacoes USING btree (processo_id, created_at DESC);
CREATE UNIQUE INDEX urbis_notificacoes_pkey ON public.urbis_notificacoes USING btree (id);
CREATE UNIQUE INDEX urbis_numeracao_faixas_pkey ON public.urbis_numeracao_faixas USING btree (id);
CREATE INDEX urbis_numeracao_faixas_usuario_id_tipo_ano_idx ON public.urbis_numeracao_faixas USING btree (usuario_id, tipo, ano);
CREATE INDEX urbis_numeracao_faixas_usuario_id_tipo_idx ON public.urbis_numeracao_faixas USING btree (usuario_id, tipo);
CREATE UNIQUE INDEX uq_numeracao_uso_faixa_numero ON public.urbis_numeracao_uso USING btree (faixa_id, numero);
CREATE UNIQUE INDEX urbis_numeracao_uso_pkey ON public.urbis_numeracao_uso USING btree (id);
CREATE INDEX urbis_numeracao_uso_processo_codigo_idx ON public.urbis_numeracao_uso USING btree (processo_codigo);
CREATE INDEX urbis_numeracao_uso_usuario_id_tipo_documento_idx ON public.urbis_numeracao_uso USING btree (usuario_id, tipo_documento);
CREATE INDEX idx_urbis_sessoes_id_status ON public.urbis_sessoes USING btree (id, status);
CREATE INDEX idx_urbis_sessoes_usuario_status ON public.urbis_sessoes USING btree (usuario_id, status);
CREATE UNIQUE INDEX urbis_sessoes_pkey ON public.urbis_sessoes USING btree (id);
CREATE INDEX urbis_sessoes_usuario_id_iniciada_em_idx ON public.urbis_sessoes USING btree (usuario_id, iniciada_em DESC);
CREATE INDEX urbis_sessoes_backup_id_status_idx ON public.urbis_sessoes_backup USING btree (id, status);
CREATE UNIQUE INDEX urbis_sessoes_backup_pkey ON public.urbis_sessoes_backup USING btree (id);
CREATE INDEX urbis_sessoes_backup_usuario_id_iniciada_em_idx ON public.urbis_sessoes_backup USING btree (usuario_id, iniciada_em DESC);
CREATE INDEX urbis_sessoes_backup_usuario_id_status_idx ON public.urbis_sessoes_backup USING btree (usuario_id, status);
CREATE UNIQUE INDEX idx_unico_diretora ON public.usuarios USING btree (perfil) WHERE (perfil = 'Diretora'::text);
CREATE UNIQUE INDEX idx_unico_gerencia_gp ON public.usuarios USING btree ((1)) WHERE (('Gerência GP'::text = ANY (perfis)) AND (status = 'Ativo'::text));
CREATE UNIQUE INDEX idx_unico_gerencia_mp ON public.usuarios USING btree ((1)) WHERE (('Gerência MP'::text = ANY (perfis)) AND (status = 'Ativo'::text));
CREATE UNIQUE INDEX idx_unico_gerencia_pp ON public.usuarios USING btree ((1)) WHERE (('Gerência PP'::text = ANY (perfis)) AND (status = 'Ativo'::text));
CREATE UNIQUE INDEX usuarios_email_key ON public.usuarios USING btree (email);
CREATE UNIQUE INDEX usuarios_pkey ON public.usuarios USING btree (id);
